# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US

reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - develop
  
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  path_filters:
    - "!**/*.md"
    - "!**/*.txt"
    - "!**/testdata/**"
  
  path_instructions:
    - path: "**/*.go"
      instructions: |
        - Follow Go best practices and idiomatic patterns
        - Ensure proper error handling
        - Check for goroutine leaks and race conditions
        - Verify nil pointer checks
        - Ensure proper resource cleanup (defer statements)
    
    - path: "**/*_test.go"
      instructions: |
        - Verify test coverage is adequate
        - Check for table-driven tests where appropriate
        - Ensure proper test cleanup
        - Validate edge cases are tested

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto

early_access: false
enable_free_tier: true
