// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MiningService exposes mining functionality to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mining$0 from "../github.com/Snider/Mining/pkg/mining/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProfile creates a new mining profile.
 */
export function CreateProfile(name: string, minerType: string, config: { [_: string]: any } | null): $CancellablePromise<$models.Profile | null> {
    return $Call.ByID(2265380910, name, minerType, config);
}

/**
 * DeleteProfile deletes a profile by ID.
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(88953983, id);
}

/**
 * GetHashrateHistory returns hashrate history for a miner.
 */
export function GetHashrateHistory(name: string): $CancellablePromise<mining$0.HashratePoint[] | null> {
    return $Call.ByID(1575569599, name);
}

/**
 * GetMinerLogs returns log lines for a specific miner.
 */
export function GetMinerLogs(name: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2396123361, name);
}

/**
 * GetMinerStats returns stats for a specific miner.
 */
export function GetMinerStats(name: string): $CancellablePromise<mining$0.PerformanceMetrics | null> {
    return $Call.ByID(938607121, name);
}

/**
 * GetProfiles returns all saved mining profiles.
 */
export function GetProfiles(): $CancellablePromise<$models.Profile[] | null> {
    return $Call.ByID(926419017);
}

/**
 * GetSystemInfo returns system information and installed miners.
 */
export function GetSystemInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(315094126);
}

/**
 * InstallMiner installs a miner of the given type.
 */
export function InstallMiner(minerType: string): $CancellablePromise<void> {
    return $Call.ByID(3895639555, minerType);
}

/**
 * ListMiners returns all running miners.
 */
export function ListMiners(): $CancellablePromise<$models.MinerStatus[] | null> {
    return $Call.ByID(2036280457);
}

/**
 * SendStdin sends input to a miner's stdin.
 */
export function SendStdin(name: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(662693835, name, input);
}

/**
 * Shutdown gracefully shuts down all miners.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(741585443);
}

/**
 * StartMiner starts a miner with the given configuration.
 */
export function StartMiner(minerType: string, config: mining$0.Config | null): $CancellablePromise<string> {
    return $Call.ByID(1889320522, minerType, config);
}

/**
 * StartMinerFromProfile starts a miner using a saved profile.
 */
export function StartMinerFromProfile(profileID: string): $CancellablePromise<string> {
    return $Call.ByID(3611345395, profileID);
}

/**
 * StopMiner stops a running miner by name.
 */
export function StopMiner(name: string): $CancellablePromise<void> {
    return $Call.ByID(854226372, name);
}

/**
 * UninstallMiner uninstalls a miner of the given type.
 */
export function UninstallMiner(minerType: string): $CancellablePromise<void> {
    return $Call.ByID(2395501368, minerType);
}
