// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mining$0 from "../github.com/Snider/Mining/pkg/mining/models.js";

/**
 * MinerInstallInfo represents installed miner information.
 */
export interface MinerInstallInfo {
    "miner_type": string;
    "is_installed": boolean;
    "version": string;
    "path": string;
}

/**
 * MinerStatus represents a running miner's status.
 */
export interface MinerStatus {
    "name": string;
    "running": boolean;
    "miner_type": string;
    "stats"?: mining$0.PerformanceMetrics | null;
}

/**
 * Profile represents a mining profile for the frontend.
 */
export interface Profile {
    "id": string;
    "name": string;
    "minerType": string;
    "config": { [_: string]: any } | null;
}

/**
 * SystemInfo represents system information for the frontend.
 */
export interface SystemInfo {
    "platform": string;
    "cpu": string;
    "cores": number;
    "memory_gb": number;
    "installed_miners_info": MinerInstallInfo[] | null;
}
