// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Config represents the configuration for a miner.
 */
export interface Config {
    "miner": string;
    "pool": string;
    "wallet": string;
    "threads": number;
    "tls": boolean;
    "hugePages": boolean;
    "algo"?: string;
    "coin"?: string;
    "password"?: string;
    "userPass"?: string;
    "proxy"?: string;
    "keepalive"?: boolean;
    "nicehash"?: boolean;
    "rigId"?: string;
    "tlsFingerprint"?: string;
    "retries"?: number;
    "retryPause"?: number;
    "userAgent"?: string;
    "donateLevel"?: number;
    "donateOverProxy"?: boolean;
    "noCpu"?: boolean;
    "cpuAffinity"?: string;
    "av"?: number;
    "cpuPriority"?: number;
    "cpuMaxThreadsHint"?: number;
    "cpuMemoryPool"?: number;
    "cpuNoYield"?: boolean;
    "hugepageSize"?: number;
    "hugePagesJIT"?: boolean;
    "asm"?: string;
    "argon2Impl"?: string;
    "randomXInit"?: number;
    "randomXNoNuma"?: boolean;
    "randomXMode"?: string;
    "randomX1GBPages"?: boolean;
    "randomXWrmsr"?: string;
    "randomXNoRdmsr"?: boolean;
    "randomXCacheQoS"?: boolean;
    "apiWorkerId"?: string;
    "apiId"?: string;
    "httpHost"?: string;
    "httpPort"?: number;
    "httpAccessToken"?: string;
    "httpNoRestricted"?: boolean;
    "syslog"?: boolean;
    "logFile"?: string;
    "printTime"?: number;
    "healthPrintTime"?: number;
    "noColor"?: boolean;
    "verbose"?: boolean;
    "logOutput"?: boolean;
    "background"?: boolean;
    "title"?: string;
    "noTitle"?: boolean;
    "pauseOnBattery"?: boolean;
    "pauseOnActive"?: number;
    "stress"?: boolean;
    "bench"?: string;
    "submit"?: boolean;
    "verify"?: string;
    "seed"?: string;
    "hash"?: string;
    "noDMI"?: boolean;

    /**
     * GPU-specific options
     * GPU device selection (e.g., "0,1,2")
     */
    "devices"?: string;

    /**
     * Mining intensity for GPU miners
     */
    "intensity"?: number;

    /**
     * Additional CLI arguments
     */
    "cliArgs"?: string;
}

/**
 * HashratePoint represents a single hashrate measurement at a specific time.
 */
export interface HashratePoint {
    "timestamp": time$0.Time;
    "hashrate": number;
}

/**
 * PerformanceMetrics represents the performance metrics for a miner.
 */
export interface PerformanceMetrics {
    "hashrate": number;
    "shares": number;
    "rejected": number;
    "uptime": number;
    "lastShare": number;
    "algorithm": string;

    /**
     * Average difficulty per accepted share (HashesTotal/SharesGood)
     */
    "avgDifficulty": number;

    /**
     * Current job difficulty from pool
     */
    "diffCurrent": number;
    "extraData"?: { [_: string]: any } | null;
}
